# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='NodeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_rate', models.IntegerField(null=True)),
                ('energy_state', models.IntegerField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NodeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_mac', models.CharField(max_length=30)),
                ('node_user', models.CharField(max_length=30)),
                ('service_limitation', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TokenTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=32, unique=True)),
                ('priority', models.IntegerField()),
                ('service_type', models.IntegerField()),
                ('service_limitation', models.IntegerField()),
                ('token_security_level', models.CharField(max_length=20)),
                ('token_start', models.DateTimeField()),
                ('timestamp', models.DateTimeField()),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='iotnode.NodeInfo')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='nodeinfo',
            unique_together=set([('node_mac', 'node_user')]),
        ),
        migrations.AddField(
            model_name='nodedata',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iotnode.NodeInfo'),
        ),
        migrations.AddField(
            model_name='file',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iotnode.NodeInfo'),
        ),
    ]
