# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-10 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iotnode', '0002_auto_20160510_1814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nodeinfo',
            options={'ordering': ['-timestamp']},
        ),
    ]
